Docker compose traefik
sunodo/sunodo pull request #225
Opened 2023-09-29 21:05 UTC by tuler

This adds a traefik to the compose environment to route to the rollups-node services.
This will make it easier to manage future services and optional exposure to the host of those services.

2023-09-30 13:24 UTC, endersonmaia submitted a review, later dismissed

2023-10-03 09:18 UTC, endersonmaia requested changes
remove first 2 commits that are already on `main` branch

2023-10-03 16:31 UTC, endersonmaia approved these changes

2023-10-03 18:41 UTC, endersonmaia approved these changes

2023-10-04 11:35 UTC, tuler commented
Please review

2023-10-04 11:38 UTC, endersonmaia approved these changes

2023-10-04 11:40 UTC, merged